Section "InputClass"
    Identifier "NVT touchscreen"
    MatchProduct "NVTCapacitiveTouchScreen"
    Driver "libinput"
EndSection

Section "InputClass"
    Identifier "NVT pen"
    MatchProduct "NVTCapacitivePen"
    Driver "libinput"
EndSection
